### ISSUE TITLE
Query: How to handle database secure connection with Aeraki

### ISSUE THREAD

**Issue by fengyebxh** [aeraki-mesh/aeraki#140]
Aeraki project is amazing, one impressing scenario is that "Manage authentication for other system, like databases". I would like to know how Aeraki handle database secure connection, like mySQL SSL connection, especially when the database certificate is issued by third party. Is there any example or guide?

**Comment by zhaohuabing** [comment]
Aeraki aims to support layer-7 processing, such as the auth settingof Redis proxy.. Your use case is actually SSL, which can be implemented directly with the native Istio egress gateway.
