### ISSUE TITLE
When the same service has multiple clusters and multiple virtual IP scenarios, the service only takes effect in one cluster configuration

### ISSUE THREAD

**Issue by Sad-polar-bear** [aeraki-mesh/aeraki#149]
**Describe the bug**
a service deploy in multiple clusters, only one cluster configuration  takes effect

**To Reproduce**
1. compare with Multi cluster with istio
2. deploy one service in Multi cluster
3. Push traffic split policy

**Comment by Sad-polar-bear** [comment]
@zhaohuabing

**Comment by zhaohuabing** [comment]
Currently, Istio only assign one vip to the address list of a
    service entry. To fix this issue, the Istio issue needs to be fixed as
    well: https://github.com/istio/istio/issues/36694
