### ISSUE TITLE
MetaRouter 规则不生效

### ISSUE THREAD

**Issue by yongxinzhang18810492456** [aeraki-mesh/aeraki#171]
我自己创建了dubbo 生产者和消费者 应用，部署 MetaRouter 规则时，规则没生效
![image](https://user-images.githubusercontent.com/33047172/155295499-d6088c7c-79fe-4010-a6ef-7a3797f19a59.png)

**Comment by zhaohuabing** [comment]
aeraki 对 Isito 的版本和配置有相关要求，请参考 https://www.aeraki.net/zh/docs/v1.0/install/ 的介绍检查安装是否正确。

建议在一个未安装 Istio 的 K8s 集群中采用 https://www.aeraki.net/zh/docs/v1.0/quickstart/ 介绍的方法安装 Istio，aeraki 和 示例程序。

**Comment by yongxinzhang18810492456** [comment]
我通过make demo 安装的，
aeraki 提供的demo，metarule规则正常，我自己写的demo，metaRule规则不生效，怎么排查这个问题？
![image](https://user-images.githubusercontent.com/33047172/155441391-722f80a8-d650-4830-8192-4fe82e5d3e5e.png)

**Comment by zhaohuabing** [comment]
看样子走的是 passthrough，没有走 vip 的 listener，你对比 aeraki 自带 demo 看一下。
