### ISSUE TITLE
启动了两个版本provider，但是每次consumer dubbo调用provider时， 都会负载到provider的一个版本

### ISSUE THREAD

**Issue by yongxinzhang18810492456** [aeraki-mesh/aeraki#182]
我启动了两个版本，但是每次consumer  dubbo调用provider时， 都会负载到provider的一个版本：
调用链路结果：

![image](https://user-images.githubusercontent.com/33047172/160046615-bc2ec178-bf73-4e90-b669-c652f3760ecc.png)

v1 版本的aeraki 路由规则配置：

![image](https://user-images.githubusercontent.com/33047172/160044302-b1ed224b-47d2-4c52-a882-7a0d8c197211.png)

v2 版本的aeraki路由规则配置：
![image](https://user-images.githubusercontent.com/33047172/160044445-f7641d76-d16e-4a8b-b2e9-daa7eae1a628.png)

**Comment by zhaohuabing** [comment]
这是你自己的程序？你按照 https://www.aeraki.net/zh/docs/v1.0/quickstart/ 的方法安装 demo 验证可以吗？
