### ISSUE TITLE
请问下使用meta-protocol方式管理dubbo流量，consumer 必须是直连的方式吗

### ISSUE THREAD

**Issue by panniyuyu** [aeraki-mesh/aeraki#191]
看了样例发现 consumer 是配置了直连的方式，自己写的 demo 不是直连方式路由规则不生效，但是修改成直连的方式路由规则生效

**Comment by zhaohuabing** [comment]
是的，Consumer 直接配置 Provider 的 ServiceEntry 的 Host。目前ServiceEntry是按照 Dubbo Interface 粒度生成的，支持 Interface 粒度的服务治理。这样才能被 sidecar 拦截。Dubbo2Istio 项目可以连接Dubbo registry（ZK，Etcd，Nacos），生成 ServiceEntry。
