### ISSUE TITLE
Lazyxds Not Work

### ISSUE THREAD

**Issue by liyongxian** [aeraki-mesh/aeraki#192]
**Describe the bug**
After Deploying Lazyxds,Adding The Service Of productpage Annotation (lazy-xds: "true"),The EDS Of productpage Should Not have Other Service's EDS. Thanks.
**To Reproduce**
1. Deploy The Lazyxds:
![image](https://user-images.githubusercontent.com/18571576/163510206-e7ebb5de-23d7-4475-87d6-e0e58311f15e.png)
2. Pods Running
![image](https://user-images.githubusercontent.com/18571576/163510393-b4e8573c-3cd0-41e2-861c-fe4c00dc3c06.png)
3.Annotation
Productpage  Service :
![image](https://user-images.githubusercontent.com/18571576/163510532-a188177d-6167-4a1a-a26c-cbfae4522a92.png)
bookinfo namespace:
![image](https://user-images.githubusercontent.com/18571576/163513629-f091a198-44ad-44ff-af61-a43aa6a30986.png)
4.  Productpage  Pod‘s  EDS:
![image](https://user-images.githubusercontent.com/18571576/163511642-fb79d1ba-b281-4c0b-b4a0-e01c4021f67b.png)
EDS Has Other EDS Info.
5. Logs
lazyxds:
[lazyxds.log](https://github.com/aeraki-mesh/aeraki/files/8493653/lazyxds.log)
egressgateway-lazyxds:
[egressgateway.log](https://github.com/aeraki-mesh/aeraki/files/8493658/egressgateway.log)

ENV：
1、k8s Version
![image](https://user-images.githubusercontent.com/18571576/163512354-5f309e41-0d1b-48f9-b86d-f5315f2850c5.png)
2、Istio Version
![image](https://user-images.githubusercontent.com/18571576/163512415-cf175040-8810-44c6-9439-7bb62cd1bf7f.png)

**Comment by liyongxian** [comment]
The ConfigMap lazyxds-als-bootstrap:
![image](https://user-images.githubusercontent.com/18571576/163514552-5895d8bb-7b03-45db-ad0b-d030663e3718.png)
The Service lazyxds.istio-system is What? Not The Service In istio-system.

**Comment by zhaohuabing** [comment]
@liyongxian  lazyxds has been moved into a standalone repo here: https://github.com/aeraki-mesh/lazyxds
Could you please move this issue to that repod?
