### ISSUE TITLE
feature Req:  can meta protocol provice some metric interface when we use codec

### ISSUE THREAD

**Issue by huanghuangzym** [aeraki-mesh/aeraki#197]
i read code about meta protocol code,their metrics are set by  upper layer，
 can  i  define  metric labels  when i write self protocol codec ?

**Comment by zhaohuabing** [comment]
It’s possible to add some decoding/encoding related metrics in the codec, but the request relates metrics should be generated in the metaprotcol framework.

Let's take a step back, why do you need to do that? Are there any labels which can't be retrieved from envs?

**Comment by huanghuangzym** [comment]
because  different  protocol  may have self special action we want to express
like mysql, maybe we want to provice req table, database ,atcion (insert or query)
like redis , maybe we care about set ? get ? or pipeline?

**Comment by huanghuangzym** [comment]
those actions ,maybe we can get  when codec the protocol?

**Comment by zhaohuabing** [comment]
I got it.

We could add these protocol-specific labels to metadata. These 'metadata' should be distinguished from other normal metadata key-values, we could use a fixed prefix, such as 'AERAKI_METRICS_'.
