### ISSUE TITLE
Helm chart is outdated

### ISSUE THREAD

**Issue by zhaohuabing** [aeraki-mesh/aeraki#199]
**Describe the bug**
The Helm chart ([manifests/charts/aeraki](https://github.com/aeraki-mesh/aeraki/tree/1879f821ecea8d6e61871abbfc307242482f6b77/manifests/charts/aeraki)) is outdated. It needs to be updated so we can use it to install aeraki.

**Comment by nevermosby** [comment]
Hi there, I wanna give it a shot. Pls assign it to me.

**Comment by zhaohuabing** [comment]
Sure, please go ahead.

**Comment by zhaohuabing** [comment]
@nevermosby Do you need help on this issue?

**Comment by nevermosby** [comment]
@zhaohuabing yes, I have read through the doc of Aeraki installation, but got nothing about helm installation guide. What's the key point of helm chart update?

**Comment by zhaohuabing** [comment]
Helm is a package manage tool for applications deployed on Kubernetes. If you don't know Helm before, this task might be a bit difficult for you.

**Comment by tyut22316** [comment]
我对helm有过学习和实践，可以申请一同参与么

**Comment by nevermosby** [comment]
@tyut22316 I've done most of the work. Could u pls help review my work when it is done?

**Comment by tyut22316** [comment]
@nevermosby 好的，您快完成的话，请继续，我也只能挑时间来抽空完成工作，需要helm的指导可以咨询我，我下班以后尝试学习实践一下

**Comment by nevermosby** [comment]
@tyut22316 谢谢 ：）
