### ISSUE TITLE
we need traffic mirroring

### ISSUE THREAD

**Issue by whitefirer** [aeraki-mesh/aeraki#200]
traffic mirroring as a common feature, mirroring  sends a copy of live traffic to a mirrored service or a traffic record&replay service.
that will help us analyze the traffic better.

**Comment by zhaohuabing** [comment]
https://github.com/aeraki-mesh/aeraki/pull/219
https://github.com/aeraki-mesh/meta-protocol-proxy/pull/61

**Comment by zhaohuabing** [comment]
https://github.com/aeraki-mesh/aeraki/pull/268

**Comment by whitefirer** [comment]
well done!
