### ISSUE TITLE
meta-protocol-proxy  have not adjust to envoy v1.20 (istio 1.12)

### ISSUE THREAD

**Issue by huanghuangzym** [aeraki-mesh/aeraki#222]
aeraki control plane alareay adjust to istio 1.12
but meta-protocol-proxy not adjust to envoy 1.20

**Comment by zhaohuabing** [comment]
Yes, it's on the plan but we don't have capacity for it right now. Any
help would be appreciated.

**Comment by huanghuangzym** [comment]
i have submit this pr 
https://github.com/aeraki-mesh/meta-protocol-proxy/pull/58      
can anyone help to review
