### ISSUE TITLE
Support swim lane

### ISSUE THREAD

**Issue by zhaohuabing** [aeraki-mesh/aeraki#264]
**Is your feature request related to a problem? Please describe.**
Swim lane is a traffic pattern to route requests inside a group of service instances based on traffic labels.  For example, we could build an isolated swim lane for each development team in the test environment. The team can deploy and test inside their only swim lane, without interfering with other teams.
![image](https://user-images.githubusercontent.com/1321762/174970723-cfaf7a5a-dc0d-45a8-a3f9-061ffb5a648f.png)

**Describe the solution you'd like**
We could define some special header with a fixed prefix, such as "x-meta-protocol-passthrough-". All applications are required to pass these headers to the upstreams.

Distributed tracing could also utilize this approach to pass the tracing context.

@whitefirer

**Comment by zhaohuabing** [comment]
> So applications should do something like deal with the tracing system.
> 
> They should manually get the "x-meta-protocol-passthrough-" header, and pass it to upstreams in the same request context.
> 
> Or maybe we should provide an SDK or something to do this automatically?

Yes, the applications are required to pass all the "x-meta-protocol-passthrough-" headers to the upstreams.

**Comment by whitefirer** [comment]
or get the pass header from crd?
