### ISSUE TITLE
cat aeraki lazyxds work with already virtualservice

### ISSUE THREAD

**Issue by huanghuangzym** [aeraki-mesh/aeraki#267]
i used aeraki lazyxds ,when client request server with existed virtualservice
the lazyxds controller will ignore the svc defined inassociation virtservice

**Comment by huanghuangzym** [comment]
![image](https://user-images.githubusercontent.com/15240576/177897939-95a7eeba-63b5-4c95-ba05-1b93056976fb.png)
![image](https://user-images.githubusercontent.com/15240576/177897957-6edc51e1-6fa5-48dd-9665-79d02ce2b9ff.png)
![image](https://user-images.githubusercontent.com/15240576/177897995-79282f42-0ed8-4cae-83c7-4747280ec5e3.png)

the first call except direct to asm-2,but actually direct to asm-1,
it seems the envoyfilter ignore it
![image](https://user-images.githubusercontent.com/15240576/177898072-1fa87149-6d81-4065-96dc-c3c53c1eecc6.png)

**Comment by huanghuangzym** [comment]
why the envoyfilter ignore virtualservice?

**Comment by zhaohuabing** [comment]
@huanghuangzym lazyxds has been moved to a [separate repository](https://github.com/aeraki-mesh/lazyxds/).
