### ISSUE TITLE
i make the simple connection timer

### ISSUE THREAD

**Issue by hbgongen** [aeraki-mesh/aeraki#270]
it can disconnect the idle connection according to your configuration.i will format my code and make a pull request soon.

**Comment by zhaohuabing** [comment]
It's for upstream or downstream?

**Comment by hbgongen** [comment]
It's a downstream idle timeout timer.



发自我的iPhone


------------------ Original ------------------
From: zhaohuabing ***@***.***&gt;
Date: Fri,Jul 29,2022 9:29 AM
To: aeraki-mesh/aeraki ***@***.***&gt;
Cc: hbgongen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [aeraki-mesh/aeraki] i make the simple connection timer (Issue#270)





 
It's for upstream or downstream?

**Comment by zhaohuabing** [comment]
Someting similar to this ?: https://github.com/zhaohuabing/meta-protocol-proxy/commit/43a8e457841a910819bcd6bac245bb89a2ba3a86

Could you please elaborate on your use case?

**Comment by hbgongen** [comment]
Yeah,if you have support idle connection timeout,i don't need to make a pr.
Recently i want to make the access log.Is this feature developing?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aeraki-mesh/aeraki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 上午9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aeraki-mesh/aeraki] i make the simple connection timer (Issue #270)





 
Someting similar to this ?: ***@***.***
 
Could you please elaborate on your use case?

**Comment by hbgongen** [comment]
our client will pre-connect to our edge-proxy(envoy),many downstream connection don't hava any request.my use case is to refer to my idle-timeout to disconnect these idle connection,in case that a huge connection number to edge proxy.i think https://github.com/zhaohuabing/meta-protocol-proxy/commit/43a8e457841a910819bcd6bac245bb89a2ba3a86 can support this.
I have completed this function and tested it well.

**Comment by zhaohuabing** [comment]
Someone has asked for setting idle_timeout for the connection pool, so I implemented this feature. However, the one who asked for this eventually decided that they don't need this anymore, that's why this feature has not been merged into master. 

An explanation of your use case would help us understand why we need this.

**Comment by zhaohuabing** [comment]
> our client will pre-connect to our edge-proxy(envoy),many downstream connection don't hava any request.my use case is to refer to my idle-timeout to disconnect these idle connection,in case that a huge connection number to edge proxy.i think [zhaohuabing/meta-protocol-proxy@43a8e45](https://github.com/zhaohuabing/meta-protocol-proxy/commit/43a8e457841a910819bcd6bac245bb89a2ba3a86) can support this. I have completed this function and tested it well.

I got it. You can go on with your PR if you have already finished testing.

**Comment by zhaohuabing** [comment]
> our client will pre-connect to our edge-proxy(envoy),many downstream connection don't hava any request.my use case is to refer to my idle-timeout to disconnect these idle connection,in case that a huge connection number to edge proxy.i think [zhaohuabing/meta-protocol-proxy@43a8e45](https://github.com/zhaohuabing/meta-protocol-proxy/commit/43a8e457841a910819bcd6bac245bb89a2ba3a86) can support this. I have completed this function and tested it well.

It seems to me that you need a timeout for downstream connections, not for upstreams.

[zhaohuabing/meta-protocol-proxy@43a8e45](https://github.com/zhaohuabing/meta-protocol-proxy/commit/43a8e457841a910819bcd6bac245bb89a2ba3a86) doesn't solve this issue. It just checks the idle time for upstream connections and closes them when no data has been sent to the upstream connection after the timeout.

**Comment by hbgongen** [comment]
OK,I am out right now.I will commit it when i come back to company.

**Comment by hbgongen** [comment]
I have make PR,you can check it.

**Comment by hbgongen** [comment]
Ok.I am out right now.I will commit it when i come back to company.



发自我的iPhone


------------------ Original ------------------
From: zhaohuabing ***@***.***&gt;
Date: Fri,Jul 29,2022 10:10 AM
To: aeraki-mesh/aeraki ***@***.***&gt;
Cc: hbgongen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [aeraki-mesh/aeraki] i make the simple connection timer (Issue#270)





  
our client will pre-connect to our edge-proxy(envoy),many downstream connection don't hava any request.my use case is to refer to my idle-timeout to disconnect these idle connection,in case that a huge connection number to edge proxy.i think ***@***.*** can support this. I have completed this function and tested it well.
  
I got it. You can go on with your PR if you have already finished testing.
