### ISSUE TITLE
remote or network error: default codec read failed: EOF

### ISSUE THREAD

**Issue by Allengf** [aeraki-mesh/aeraki#278]
**Describe the bug**
I use the zijie kitex thrift protocol client to report an error in Aeraki 

**Additional context**

**Comment by Allengf** [comment]
Does it support kitex framework?
example: 
client.WithTransportProtocol(transport.TTHeader)

**Comment by zhaohuabing** [comment]
Aeraki Mesh haven't  been tested with kitex. The supported wire encoding for thrift  are Binary,LaxBinary,Compact,Twitter, and Auto.
