### ISSUE TITLE
helm安装时ApplicationProtocol找不到

### ISSUE THREAD

**Issue by lilai23** [aeraki-mesh/aeraki#290]
**Describe the bug**
helm进行安装时提示no matches for kind "ApplicationProtocol" in version "metaprotocol.aeraki.io/v1alpha1

**Additional context**
$ helm install aeraki ./aeraki -n istio-system
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "dubbo" namespace: "" from "": no matches for kind "ApplicationProtocol" in version "metaprotocol.aeraki.io/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "thrift" namespace: "" from "": no matches for kind "ApplicationProtocol" in version "metaprotocol.aeraki.io/v1alpha1"
ensure CRDs are installed first]

**Comment by zhaohuabing** [comment]
I believe that the Helm template is out of date.
