### ISSUE TITLE
Aeraki Mesh performance testing

### ISSUE THREAD

**Issue by xj524598** [aeraki-mesh/aeraki#299]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhaohuabing** [comment]
Yangshiping（央视频) had a test and we shared that result in this presentation: https://www.zhaohuabing.com/post/2022-03-30-aeraki-mesh-winter-olympics-practice/

![Screenshot 2023-01-30 at 10 03 00](https://user-images.githubusercontent.com/1321762/215372383-02421c25-4412-4070-9af1-fc4cff403182.png)
