### ISSUE TITLE
Support MetaProtocol(Non  HTTP layer 7 protocols) at ingress gateway

### ISSUE THREAD

**Issue by zhaohuabing** [aeraki-mesh/aeraki#303]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhaohuabing** [comment]
@panniyuyu Could you please submit another PR with documentation so that we can wrap this up?

**Comment by panniyuyu** [comment]
Of course
