### ISSUE TITLE
是否可开放aeraki扩展治理能力的接口

### ISSUE THREAD

**Issue by wuyouxia123** [aeraki-mesh/aeraki#305]
我们需要对于aeraki现有的治理能力进行扩展，新增“API级粒度的熔断能力“和“API级粒度的并发限流”能力
但是对于管理面，新增细粒度的治理能力需要做一些必要的入侵，请问是否可以提供通用接口来用于扩展新的治理能力？

对于数据面，我们可以参照meta-protocol-proxy/src/meta_protocol_proxy/filters来无侵入的扩充治理能力
但是对于管理面，如果新增治理能力，需要对至少三处进行侵入式修改
1. 新增CircuitBreaking和ConnectionLimit的配置选项（aeraki/api/metaprotocol/v1alpha1/metaprotocol_metarouter.proto）
![image](https://user-images.githubusercontent.com/126319688/221348762-a3385322-465e-4845-99fa-9487fdd7d6cf.png)

2. validating webhook允许部署只包含新配置项的yaml （aeraki/pkg/webhook/validation/scheme/validation.go）
![image](https://user-images.githubusercontent.com/126319688/221348791-a08e27a2-aa8a-4e37-b776-a3c1fe2018f8.png)

3. 转换配置到filter（aeraki/plugin/metaprotocol/filters.go）
![image](https://user-images.githubusercontent.com/126319688/221348857-7643f652-1ec1-486b-bcb9-7c9281fdcc44.png)

请问是否可提供通用接口来无侵入式的新增治理能力？或者对于这两个能力的代码是否可合入社区？

**Comment by zhaohuabing** [comment]
听上去像是可以做成通用的能力？可以讨论一下是否能直接合入到社区。

**Comment by zhaohuabing** [comment]
@ wuyouxia123 你在 Aeraki Mesh 社区微信群里面吗？如果不在的话，请给我发邮件 zhaohuabing@gmail.com，我把你拉进群里。

**Comment by wuyouxia123** [comment]
你好，已发送请求加入社区的邮件
邮件名：wuyouxia123请求加入aeraki微信社区
账号：youxia.wu@foxmail.com

**Comment by zhaohuabing** [comment]
@wuyouxia123 经过讨论可以作为通用需求合入，因此关闭该 issue。需要合入的功能请另外提 issue 跟踪。
