### ISSUE TITLE
Install the Aeraki, Istio and demo apps.

### ISSUE THREAD

**Issue by Webster-Yang** [aeraki-mesh/aeraki#308]
sudo make demo
bash demo/install-demo.sh default
++ istioctl version --remote=false
++ grep 1.14.5
demo/../test/e2e/scripts/istio.sh: 行 25: istioctl：未找到命令
+ '[' -n '' ']'
+ curl -L https://istio.io/downloadIstio
+ ISTIO_VERSION=1.14.5
+ sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   101  100   101    0     0    255      0 --:--:-- --:--:-- --:--:--   255
100  4856  100  4856    0     0   5029      0 --:--:-- --:--:-- --:--:--     0

Downloading istio-1.14.5 from https://github.com/istio/istio/releases/download/1.14.5/istio-1.14.5-linux-amd64.tar.gz ...

https://github.com/istio/istio/releases/download/1.14.5/istio-1.14.5-linux-amd64.tar.gz is not found, please specify a valid ISTIO_VERSION and TARGET_ARCH
+ '[' -z 1.2.3 ']'
+ '[' -z '' ']'
+ export AERAKI_ISTIOD_ADDR=istiod.istio-system:15010
+ AERAKI_ISTIOD_ADDR=istiod.istio-system:15010
+ '[' -z '' ']'
+ export AERAKI_NAMESPACE=istio-system
+ AERAKI_NAMESPACE=istio-system
+ '[' -z '' ']'
+ export AERAKI_IS_MASTER=true
+ AERAKI_IS_MASTER=true
+ '[' -z '' ']'
+ export AERAKI_ENABLE_ENVOY_FILTER_NS_SCOPE=false
+ AERAKI_ENABLE_ENVOY_FILTER_NS_SCOPE=false
+ mkdir -p /root/.aeraki
+ envsubst
+ '[' '' == mode=tcm ']'
+ kubectl delete crd applicationprotocols.metaprotocol.aeraki.io
E0307 19:26:08.290148  115841 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:08.290638  115841 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:08.291768  115841 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:08.293522  115841 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:08.295113  115841 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
+ true
+ kubectl apply -f demo/../test/e2e/scripts/../../../k8s/crd.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
install default demo
The connection to the server localhost:8080 was refused - did you specify the right host or port?
meta-dubbo
E0307 19:26:09.283134  116193 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.283578  116193 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.285297  116193 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.286790  116193 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.288205  116193 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0307 19:26:09.404967  116243 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.405502  116243 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.406948  116243 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.408642  116243 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.410192  116243 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?

demo/../demo/metaprotocol-dubbo/../common_func.sh: 第 26 行： [: !=：需要一元表达式
E0307 19:26:09.541825  116285 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.542267  116285 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.543837  116285 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.545232  116285 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:09.546632  116285 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
meta-thrift
E0307 19:26:10.179347  116505 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.179923  116505 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.181334  116505 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.182870  116505 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.184307  116505 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0307 19:26:10.308496  116554 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.308950  116554 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.310468  116554 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.311473  116554 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.312917  116554 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?

demo/../demo/metaprotocol-thrift/../common_func.sh: 第 26 行： [: !=：需要一元表达式
E0307 19:26:10.440986  116597 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.441685  116597 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.443453  116597 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.444984  116597 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0307 19:26:10.446543  116597 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
error: failed to create configmap: Post "http://localhost:8080/api/v1/namespaces/meta-thrift/configmaps?fieldManager=kubectl-create&fieldValidation=Strict": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
make: *** [Makefile:47：demo] 错误 1

**Comment by zhaohuabing** [comment]
@Webster-Yang It looks like the kubectl can't access the Kubernetes API Server on localhost:8080
