### ISSUE TITLE
Image pull timed out

### ISSUE THREAD

**Issue by Webster-Yang** [aeraki-mesh/aeraki#313]
background：

Linux tv3--c9d4bf90 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/docker/daemon.json
{
  "registry-mirrors": [
   "https://mm1pl1bo.mirror.aliyuncs.com",
   "http://hub-mirror.c.163.com",
    "https://docker.mirrors.ustc.edu.cn",
    "https://registry.docker-cn.com",
    "https://registry.aliyuncs.com",
   "https://hub.daocloud.io"
  ]
}

 kubectl get pods -A
NAMESPACE            NAME                                           READY   STATUS             RESTARTS       AGE
istio-system         aeraki-6b585f5df7-knsbn                        0/1     ImagePullBackOff   0              3d5h
istio-system         grafana-79c4bf89d4-g4zzn                       0/1     ImagePullBackOff   0              3d5h
istio-system         istio-ingressgateway-6bf8949fb4-nmp52          0/1     ImagePullBackOff   0              46m
istio-system         istio-ingressgateway-fd86fcd4d-vbd4j           0/1     ImagePullBackOff   0              44h
istio-system         istiod-678b47f474-7gsc7                        0/1     ImagePullBackOff   0              51m
istio-system         istiod-fbff8d667-9cd5x                         0/1     ImagePullBackOff   0              44h
istio-system         jaeger-649966d89-f6fxv                         0/1     ImagePullBackOff   0              3d5h
istio-system         prometheus-67669bc6c8-c82cp                    0/2     ErrImagePull       0              3d5h
kube-system          coredns-565d847f94-wqqwf                       1/1     Running            10 (28h ago)   3d5h
kube-system          coredns-565d847f94-xcljv                       1/1     Running            10 (28h ago)   3d5h
kube-system          etcd-mesh-control-plane                        1/1     Running            0              28h
kube-system          kindnet-6vgc7                                  1/1     Running            10 (28h ago)   3d5h
kube-system          kindnet-bq29j                                  1/1     Running            10 (28h ago)   3d5h
kube-system          kube-apiserver-mesh-control-plane              1/1     Running            0              28h
kube-system          kube-controller-manager-mesh-control-plane     1/1     Running            10 (28h ago)   3d6h
kube-system          kube-proxy-89jgn                               1/1     Running            10 (28h ago)   3d5h
kube-system          kube-proxy-blmq8                               1/1     Running            10 (28h ago)   3d5h
kube-system          kube-scheduler-mesh-control-plane              1/1     Running            10 (28h ago)   3d6h
local-path-storage   local-path-provisioner-684f458cdd-6zwkr        1/1     Running            16 (28h ago)   3d5h
meta-dubbo           dubbo-sample-consumer-7595987fb4-tg984         0/1     ImagePullBackOff   0              3d5h
meta-dubbo           dubbo-sample-provider-v1-759846fc48-9jk4z      0/1     ImagePullBackOff   0              3d5h
meta-dubbo           dubbo-sample-provider-v2-586468f795-r4hlp      0/1     ImagePullBackOff   0              3d5h
meta-dubbo           dubbo-sample-second-provider-7dc5b98b6-f4pk2   0/1     ErrImagePull       0              3d5h
meta-thrift          rate-limit-server-75cbff8d86-nw845             0/2     ErrImagePull       0              3d5h
meta-thrift          thrift-sample-client-7dc7d49f7b-ltz6k          0/1     ImagePullBackOff   0              3d5h
meta-thrift          thrift-sample-server-v1-bbb6b8c74-crvsk        0/1     ImagePullBackOff   0              3d5h
meta-thrift          thrift-sample-server-v2-66767687cf-wg7z4       0/1     ImagePullBackOff   0              3d5h

kubectl describe pod istiod-fbff8d667-9cd5x   -n  istio-system
Name:             istiod-fbff8d667-9cd5x
Namespace:        istio-system
Priority:         0
Service Account:  istiod
Node:             mesh-worker/172.18.0.2
Start Time:       Thu, 09 Mar 2023 23:31:04 +0800
Labels:           app=istiod
                  install.operator.istio.io/owning-resource=unknown
                  istio=pilot
                  istio.io/rev=default
                  operator.istio.io/component=Pilot
                  pod-template-hash=fbff8d667
                  sidecar.istio.io/inject=false
Annotations:      prometheus.io/port: 15014
                  prometheus.io/scrape: true
                  sidecar.istio.io/inject: false
Status:           Pending
IP:               10.244.1.13
IPs:
  IP:           10.244.1.13
Controlled By:  ReplicaSet/istiod-fbff8d667
Containers:
  discovery:
    Container ID:  
    Image:         istio/pilot:1.14.5
    Image ID:      
    Ports:         8080/TCP, 15010/TCP, 15017/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      discovery
      --monitoringAddr=:15014
      --log_output_level=default:debug
      --domain
      cluster.local
      --keepaliveMaxServerConnectionAge
      30m
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      500m
      memory:   2Gi
    Readiness:  http-get http://:8080/ready delay=1s timeout=5s period=3s #success=1 #failure=3
    Environment:
      REVISION:                                     default
      JWT_POLICY:                                   third-party-jwt
      PILOT_CERT_PROVIDER:                          istiod
      POD_NAME:                                     istiod-fbff8d667-9cd5x (v1:metadata.name)
      POD_NAMESPACE:                                istio-system (v1:metadata.namespace)
      SERVICE_ACCOUNT:                               (v1:spec.serviceAccountName)
      KUBECONFIG:                                   /var/run/secrets/remote/config
      ENABLE_LEGACY_FSGROUP_INJECTION:              false
      PILOT_TRACE_SAMPLING:                         1
      PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND:  true
      PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND:   true
      ISTIOD_ADDR:                                  istiod.istio-system.svc:15012
      PILOT_ENABLE_ANALYSIS:                        false
      CLUSTER_ID:                                   Kubernetes
    Mounts:
      /etc/cacerts from cacerts (ro)
      /var/run/secrets/istio-dns from local-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pmptz (ro)
      /var/run/secrets/remote from istio-kubeconfig (ro)
      /var/run/secrets/tokens from istio-token (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  local-certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  cacerts:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cacerts
    Optional:    true
  istio-kubeconfig:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-kubeconfig
    Optional:    true
  kube-api-access-pmptz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Normal   BackOff  47m (x5031 over 28h)  kubelet  Back-off pulling image "istio/pilot:1.14.5"
  Warning  Failed   5m4s (x232 over 28h)  kubelet  Failed to pull image "istio/pilot:1.14.5": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/istio/pilot:1.14.5": failed to resolve reference "docker.io/istio/pilot:1.14.5": failed to do request: Head "https://registry-1.docker.io/v2/istio/pilot/manifests/1.14.5": dial tcp 44.205.64.79:443: i/o timeout
  Warning  Failed   5m4s (x232 over 28h)  kubelet  Error: ErrImagePull

**Comment by Xunzhuo** [comment]
Hey @Webster-Yang, could you quote the logs with markdown syntax? This is easy to read.
