### ISSUE TITLE
下载meta-protocol-awesomerpc项目之后，按照官网教程，没有build.sh

### ISSUE THREAD

**Issue by voidstatic888** [aeraki-mesh/aeraki#328]
项目代码中没有build.sh，而且最终build出来的是什么？扩展后的Envoy么？istio怎么使用这个编译出来的Envoy呀？麻烦有大佬帮解答下么？或者发下参考信息的url

**Comment by voidstatic888** [comment]
我想实现自己的私有rpc协议

**Comment by zhaohuabing** [comment]
https://github.com/aeraki-mesh/meta-protocol-proxy#build
