### ISSUE TITLE
如何针对dubbo interface配置限流

### ISSUE THREAD

**Issue by luckyboysmith** [aeraki-mesh/aeraki#345]
**Describe the bug**
目前按照demo，已实现 通过dubbo2istio将 服务封装为 serviceEntries,
同时 参考demo修改了业务代码，实现了 consumer通过 serviceEntries的host直连provider的dubbo调用，
现在 生产环境存在 对 dubbo接口进行限流配置的场景，尝试新建MetaRouter，未生效
希望得到帮助，谢谢

ServiceEntries配置如下图所示，方法为com.smy.gts.service.ErrCodeManagerOmsService，
![image](https://user-images.githubusercontent.com/23690787/234239044-9b42b112-2840-49e6-9e20-7e339b06370f.png)
![image](https://user-images.githubusercontent.com/23690787/234239148-caed4bab-3b21-45b7-8435-0ca0d5df6c0a.png)

MetaRouter配置如下图所示，
![image](https://user-images.githubusercontent.com/23690787/234238387-3399b1ef-c39a-4cc4-89bb-5d3afc0797cf.png)

**Comment by luckyboysmith** [comment]
Kiali Graph如下
![image](https://user-images.githubusercontent.com/23690787/234241339-318f9d04-2edd-4c69-a71b-9e073d0585d7.png)

**Comment by zhaohuabing** [comment]
你看一下 envoy sidecar 里面有没有对应的 MetaProtocolProxy 配置，以及该配置中是否有限流的相关参数

**Comment by luckyboysmith** [comment]
> 你看一下 envoy sidecar 里面有没有对应的 MetaProtocolProxy 配置，以及该配置中是否有限流的相关参数

你好，已发送请求加入社区的邮件
邮件名：luckyboysmith请求加入aeraki微信社区

**Comment by luckyboysmith** [comment]
验证可以了，是自己搞错了，closed
