### ISSUE TITLE
when to support istio 1.16

### ISSUE THREAD

**Issue by huanghuangzym** [aeraki-mesh/aeraki#349]
by istio support policy, we should adapt aeraki mesh to istio newer version as soon as?
like 1.16  ? 

ttps://istio.io/latest/docs/releases/supported-releases/

**Comment by zhaohuabing** [comment]
I plan to work on it after
https://github.com/aeraki-mesh/meta-protocol-proxy/pull/101is reviewed and
merged. Would appreciate any help on this.

**Comment by huanghuangzym** [comment]
which version suggest to adapt ?  1.16  or feature 1.18 ?

**Comment by zhaohuabing** [comment]
I prefer 1.16 since the current supported Istio version is 1.14. What's
your recommendation?

**Comment by huanghuangzym** [comment]
done
