### ISSUE TITLE
aeraki和采用envoy作为代理的云原生网关的案例

### ISSUE THREAD

**Issue by fengyeall111** [aeraki-mesh/aeraki#351]
有没有metaprotocol和采用envoy作为代理的云原生网关结合的案例，例如higress，不需要完整的istio，只使用了pilot组件

**Comment by zhaohuabing** [comment]
有的，这个 PR 就实现了网关的案例。你可以在群里面联系一下这个同学。
https://github.com/aeraki-mesh/aeraki/pull/318
