### ISSUE TITLE
Request for upgrading istio to 1.18

### ISSUE THREAD

**Issue by HEIBAIJIE** [aeraki-mesh/aeraki#365]
Istio 1.16 has been "End Of Life" by Jul 25. It is not offically supported any more.
Please consider upgrade aeraki and metaprotocol proxy to adapt istio 1.18.

https://istio.io/latest/docs/releases/supported-releases/

**Comment by zhaohuabing** [comment]
We can kick up upgrading after the [refractory](https://github.com/aeraki-mesh/aeraki/pull/366) is done.
