### ISSUE TITLE
【baidu】request to join steering committee

### ISSUE THREAD

**Issue by tanjunchen** [aeraki-mesh/aeraki#372]
I come from Baidu, and Baidu has contributed a lot of features to aeraki-mesh, such as supporting the third-party protocol bRPC, releasing aeraki 1.3.0, optimizing code logic, etc. Aeraki-mesh is currently in the testing and promotion stage in Baidu.
So, I would like to be part of the Aeraki-mesh Steering Committee. I want to join Aeraki-Mesh and make more contribution to it.

**Comment by zhaohuabing** [comment]
@tanjunchen Do you want to join as an individual or as a representative of an organization?

**Comment by tanjunchen** [comment]
> @tanjunchen Do you want to join as an individual or as a representative of an organization?

updated.
