### ISSUE TITLE
Aeraki连接istiod 15012加密端口失败

### ISSUE THREAD

**Issue by wuyouxia123** [aeraki-mesh/aeraki#389]
![image](https://github.com/aeraki-mesh/aeraki/assets/126319688/c49af893-5cb0-402c-8814-fdc5d861cb95)

![image](https://github.com/aeraki-mesh/aeraki/assets/126319688/b60d0f88-4c05-4f65-8868-aaa2886d3b89)

**Comment by zhaohuabing** [comment]
It works in e2e tests. How can I reproduce this issue?

**Comment by wuyouxia123** [comment]
env AERAKI_ISTIOD_ADDR使用istiod.istio-system.svc:15012
![image](https://github.com/aeraki-mesh/aeraki/assets/126319688/fc3d5dd6-b1d1-4eb4-913b-9fc0936ad423)
